# .streamlit/secrets.toml
# Replace these with your actual Supabase credentials

SUPABASE_URL = "https://patvtuekuadlhnvihunh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhdHZ0dWVrdWFkbGhudmlodW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NzYzOTcsImV4cCI6MjA4NzA1MjM5N30.gvIlhzNyfgWgolsrMa1yD7vwkLGfMVPI3G-_cy2Tc80"
